apiVersion: v1
kind: Namespace
metadata:
  name: gmoraga
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gmoraga-cm
  namespace: gmoraga
data:
  USERNAME: "gamg"
---
apiVersion: v1
kind: Secret
metadata:
  name: gmoraga-sc
  namespace: gmoraga
type: Opaque
stringData:
  API_KEY: "3nTTHe<Qiq[O*yNgpkBG"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmoraga-dp
  namespace: gmoraga
  labels:
    app: gmoraga-app-backend-test-lab3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gmoraga-app-backend-test-lab3
  template:
    metadata:
      labels:
        app: gmoraga-app-backend-test-lab3
    spec:
      containers:
      - name: backend-gmoraga
        image: gmoragacm/backend-test-lab3
        imagePullPolicy: Always
        env:
          - name: NODE_ENV
            value: development
          - name: USERNAME
            valueFrom:
              configMapKeyRef:
                name: gmoraga-cm
                key: USERNAME
                optional: true
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: gmoraga-sc
                key: API_KEY
                optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: gmoraga-svc
  namespace: gmoraga
  labels:
    app: gmoraga-app-backend-test-lab3
spec:
  selector:
    app: gmoraga-app-backend-test-lab3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000